# Generated by Django 2.1.4 on 2018-12-31 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportmessage', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledreportgroup',
            name='scheduled_report',
        ),
        migrations.AddField(
            model_name='scheduledreportgroup',
            name='scheduled_report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relatedscheduledreport', to='core.ScheduledReport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledreportgroup',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.Report'),
            preserve_default=False,
        ),
    ]
